### ISSUE TITLE
Progress is always on one interface - Error: [WinError 3] （FileNotFoundError)

### ISSUE THREAD

**Issue by jxaflxb** [cutright/DVH-Analytics#13]
Hi，I meet one problem，After I import my didom files with superuser account，Progress is always in this interface as the picture shows，postgrel ver:11.5，pgadmin ver:4
![image](https://user-images.githubusercontent.com/36333183/64528937-445db080-d33c-11e9-97f7-6f64b0b6e026.png)

**Comment by cutright** [comment]
It looks like it crashed, can you share your terminal output?

I’m currently out of town and will be through the weekend, so might be a while before I can respond.

**Comment by jxaflxb** [comment]
(base) C:\Users\admin\Desktop\DVH-Analytics-0.6.1>python dvha_app.py
WARNING: No PTV found for 2.16.840.1.113669.2.931128.625542426.20180518135811.894737
Skipping PTV related calculations.
Error: [WinError 3] （FileNotFoundError）。: 'C:\\Users\\admin\\18-232'
Import incomplete. Any studies successfully imported were transferred to your imported folder:
C:\Users\admin\Apps\dvh_analytics\data\imported
If a study was partially imported, all data has been removed from the database and its DICOM files remain in your inbox.
Error: [WinError 3] （ FileNotFoundError）Error: FileNotFoundError: [Errno 2] No such file or directory:: 'C:\\Users\\admin\\D383956'
Import incomplete. Any studies successfully imported were transferred to your imported folder:
C:\Users\Error: FileNotFoundError: [Errno 2]C:\\admin\Apps\dvh_analytics\data\imported
If a study was partially imported, all data has been removed from the database and its DICOM files remain in your inbox.

**Comment by cutright** [comment]
I wonder if the remove_empty_folders isn't behaving with your environment.  Can you go to DVH-Analytics/dvha/models/import_dicom.py and comment out line 1121 which requests a call for this function?  Then try importing again?

<img width="814" alt="image" src="https://user-images.githubusercontent.com/4778878/65156632-070cb900-d9f5-11e9-94f0-c6ac14678e60.png">

**Comment by jxaflxb** [comment]
I followed your instruction and imported my dicom files again, It's  the same hint: FileNotFoundError

**Comment by cutright** [comment]
There's another line of code that moves files. Try commenting out line 1244.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/4778878/65251557-24a55580-dabd-11e9-8df3-49648140eaf6.png">

Hopefully that works because I'm at a loss otherwise.

Are any of your DICOM files used for multiple plans (e.g., the same structure file for two RT Plan or Dose files)? That should be OK, but maybe I'm not properly handling your scenario.

**Comment by jxaflxb** [comment]
Thanks a lot ,it works successfully.
dicom files just exported from pinnacle 3 TPS,there is only one plans .

**Comment by cutright** [comment]
Unfortunately, commenting that line is not a permanent fix as some parts are DVHA may reference the original DICOM file at some point, so it will need to be moved to the imported folder.

Have you come across any other errors?

What is the displayed import directory in user settings? And does this directory exist?
<img width="550" alt="image" src="https://user-images.githubusercontent.com/4778878/65434550-9e528180-dde4-11e9-9474-de2b1dc55887.png">


Are your DICOM files spread across multiple directories? I think I see two in your printed output:
C:\\Users\\admin\\18-232
C:\\Users\\admin\\D383956

**Comment by jxaflxb** [comment]
I check it again, the inbox and imported folder cannot direct to my set folder(18-232,D383956) even though new folders are create，both the folder are system default account folder.
![image](https://user-images.githubusercontent.com/36333183/65498587-bd3d3a80-deee-11e9-8d6c-1a6e080f6f4a.png)

**Comment by cutright** [comment]
I think you're running into permission issues with python and your OS. I'll work on adding a warning if your inbox, imported, and selection in the Import wizard folders don't have write privileges.

If you undo all of the commenting I suggested in this post/thread (i.e., revert to original code), set your inbox and imported directories to directories within your user folder, place your files in the new inbox... does importing work OK?

**Comment by jxaflxb** [comment]
after undoing all of the suggested comment, i set my own folders,while the folders are not working when import or set again

**Comment by cutright** [comment]
I haven't heard this issue come up from others, so I'm going to close the issue since I can't reproduce the problem.  The only locations I can think of that may cause your issue are:

https://github.com/cutright/DVH-Analytics/blob/900b3df6e97ba7331db6914fb97463f609595b4e/dvha/models/import_dicom.py#L1288-L1302

https://github.com/cutright/DVH-Analytics/blob/900b3df6e97ba7331db6914fb97463f609595b4e/dvha/tools/utilities.py#L407-L423

The patch I suggested above prevents `ImportWorker.move_files()` from running, but it seems more likely `move_files_to_new_path()` in utilities.py is causing your problem.  What's perplexing is that the code checks that the file exists before acting.  Perhaps it's manifested from a threading issue?  I'm really not sure.

If you or anyone else is able to provide more details or a potential fix, I'd be happy to reopen the issue.
