### ISSUE TITLE
Feature request. CV and DV metrics (Mayo-Syntax)

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#147]
Hi Dan,

can you please add CV- and DV- metrics/endpoints from the Mayo-Syntax (from the AAPM-Task Group 263-report). I think would be very nice and important for many studies.

Here is the paper:
https://www.sciencedirect.com/science/article/pii/S0360301617342323

![Mayo-Beispiel](https://user-images.githubusercontent.com/44711812/109421869-6b4cee00-79d9-11eb-8f21-22942b2f1776.png)

**Comment by cutright** [comment]
I was thinking of adding units in the short-hand notation recently, to solve a bug related to adding end points with the same (current) short-hand but different units.  Shouldn't be hard to add DC and CV.

**Comment by cutright** [comment]
It needs some testing, but the v0.9.7 branch supports CV and DC metrics.  I also added the output units into the short-hand label.

<img width="559" alt="Screen Shot 2021-04-12 at 7 54 23 PM" src="https://user-images.githubusercontent.com/4778878/114480836-ee608700-9bc8-11eb-9d28-e5359526ac1e.png">

**Comment by Kiragroh** [comment]
Perfect. Very nice addition. I will try it this week. Thanks

**Comment by cutright** [comment]
FYI, the actual calculations are in the following lines. I *think* it's correct, but the relative dose (line 339) might be different than the TG263 definition?

And the `self.count` is in there because I add the statistical DVHs at the end of data (poor design, sorry).

https://github.com/cutright/DVH-Analytics/blob/7fe3cdcd37c60a12a7135e3d61efcf79cdff7c66/dvha/models/dvh.py#L335-L339

https://github.com/cutright/DVH-Analytics/blob/7fe3cdcd37c60a12a7135e3d61efcf79cdff7c66/dvha/models/dvh.py#L394-L398

**Comment by cutright** [comment]
I'm going to push this to master for v0.9.7 shortly... hopefully the calcs are right :)
