### ISSUE TITLE
Suport structure DVH to long time to calculate 

### ISSUE THREAD

**Issue by bozhikovstanislav** [cutright/DVH-Analytics#150]
I have found that Suport Structure should me remove from importing DVH . so to speed importing bach patients

**Comment by cutright** [comment]
You should remove it from your ROI Map if you do not want the DVH to be calculated.  I'd recommend this for Body/External as well.  Unless there's a use case to map an ROI and not want the dose?

**Comment by bozhikovstanislav** [comment]
Actualy I remove the SUPORT type "just edit the code ".. to achive fast calculation  of 1800 plans .... :)

**Comment by cutright** [comment]
1800 plans!! Awesome!

**Comment by bozhikovstanislav** [comment]
it takes 2 days ...

**Comment by cutright** [comment]
Glad to hear someone else is pushing DVHA to limits.  A few thoughts that may or may not be helpful:

* You *could* import using different DVHA instances into different databases. Then merge the databases.  Although, I don't know of anyone other than me who has tried the database merging (hopefully no issues).  If you happen to be using postgreSQL you might not even have to import into separate databases since it can handle multiple simultaneous connections.

* If you're not interested in overlap histogram data, set the resolution to 0 in preferences and the import will skip that.  I haven't optimized that algorithm, so it often fails for large structures (on Windows anyway), just wasting your time.

* It might be worth tweaking the "small volume" DVH calculation options in preferences as well.
