### ISSUE TITLE
"You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale. Things are going to break, please only change locale by creating wxLocale objects to avoid this!"

### ISSUE THREAD

**Issue by sama2689** [cutright/DVH-Analytics#159]
Installed dvha via pip in anaconda and tried to run it by entering `dvha `into the cme.exe terminal in windows. After this I got the following error as dvha did not launch

```
(Python38) C:\Users\user>dvha
ERROR: Unhandled exception: Traceback (most recent call last):
  File "d:\users\user\anaconda3\envs\python38\lib\site-packages\dvha\main.py", line 1853, in OnInit
    self.frame = DVHAMainFrame(None, wx.ID_ANY, "")
  File "d:\users\user\anaconda3\envs\python38\lib\site-packages\dvha\main.py", line 218, in __init__
    self.__add_tool_bar()
  File "d:\users\user\anaconda3\envs\python38\lib\site-packages\dvha\main.py", line 308, in __add_tool_bar
    bitmap = wx.Bitmap(ICONS[key], wx.BITMAP_TYPE_ANY)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

OnInit returned false, exiting...
```

Does this mean the package has not been installed properly?

**Comment by cutright** [comment]
This is a duplicate issue of [Issue 158](https://github.com/cutright/DVH-Analytics/issues/158).

I have a potential fix in v0.9.7, but I haven't pushed it to master (or PyPI) yet.

Are you able to run the executable instead? You can download it here: https://github.com/cutright/DVH-Analytics/releases/latest

**Comment by sama2689** [comment]
Thanks! Yes I can run the executable just fine. However I was hoping to run the commands I was interested in directly from python. The main reason for this is that I want to compute many different overlaps of multiple ROIs from various RT-struct files in various directories so will need to call the overlap function repeatedly. Would it be fixed if I used python 3.7 instead of 3.8?

**Comment by sama2689** [comment]
update: using python 3.7 fixed the issue, relatively easy to do with conda environments.

**Comment by cutright** [comment]
OK, this is good news. As you suggested, the Windows executable uses python 3.7, so this is *probably* a python 3.8 issue (as you have installed).

You have a few potential solutions:
* Install DVHA into a python 3.7 environment
* Upgrade to the latest, unreleased version:
  * `pip install https://github.com/cutright/DVH-Analytics.git@v0.9.7 --upgrade`
* Manually edit main.py as suggested by another user [here](https://github.com/cutright/DVH-Analytics/issues/158#issue-867923715)

But if you're only interested in using the functions, the above error won't cause any issues for your purpose because it only happens when you launch the GUI.
