### ISSUE TITLE
ROI map file sharing

### ISSUE THREAD

**Issue by albertelonjobs** [cutright/DVH-Analytics#54]
The current system is designed that all ROI map files are stored in the user's application folder. This will be a problem when multiple users are modifying and sharing both the institutional and the physician's ROI maps. It would be better that a user can specify the path of the ROI map files in the User Settings window. In this way, all uses have the options to share the ROI map files.

**Comment by cutright** [comment]
It's a good thought, although multiple users sharing the same text file that needs write access is problematic.

I'll have to think about the best way to address it.  I'm inclined to store the ROI Map in the SQL database, but if you're a SQLite user, that doesn't help.  And I also like the idea of DVHA users being able to give their map to a colleague... so I'd need to add an export feature too.  Maybe I should create an ROI Map import/merge feature too.

Since I know you're running from source code, you could edit `PREF_DIR` in `dvha/paths.py`, and change it to a hard-coded directory.

https://github.com/cutright/DVH-Analytics/blob/faa999e7f2145195c00b76aa0c82b7902a5d7bbc/dvha/paths.py#L21

It's possible DVHA could crash if multiple users are trying to write to the ROI Map at the same time, it's also possible you could lose data since there can be quite a bit of time between loading the file and then writing to it.  DVHA assumes the existence of a user folder and creates the DVHA specific folders if needed, so if your new PREF_DIR isn't accessible, DVHA will probably crash.

**Comment by cutright** [comment]
Sorry, I can't think of a way to implement this safely without significant rewrites.  Hopefully the manual source code edit is sufficient for you.
