### ISSUE TITLE
Reference for publication or talks in public

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#56]
Hi,
I evolve each week in understanding the code of DVHA and have began to change and add some code for my use cases.
- I export all DVH-plots to svg in specific size to have a high resolution plot for slides and so on
- I add some things to query (maybe eclipse specific: OperatorsName: physicists approver, ReviewerName: physician approver, specific Brainlab Elements-Module: hidden in a specific private dicomTag after export to eclipse)

Still this is all your work and I really want to reference you in papers or presentations if I use output or plots from your program. Do you have guidelines or a preferred way to do this.

Kind regards,
Max

**Comment by cutright** [comment]
Thanks Max!  It sounds like you're the exact reason open-source code is wonderful.

You can simply point to dvhanalytics.com (currently this just sends you to the GitHub page) and the JACMP reference in the ["Cite" ](https://github.com/cutright/DVH-Analytics#cite) section on the readme/front-page.

I have no guide lines... just winging this project day-by-day.

Both of your bullet points are great ideas.  I've been thinking about the 2nd one for while, it just hasn't been a priority.  The first one is probably relatively easy to implement, but hasn't crossed my mind to export something other than CSV or the html (like is currently available).

**Comment by Kiragroh** [comment]
Great. Thanks. I will do that. Please keep up the good work.

The svg-part is really easy to implement but the only way to get a plot in good resolution. HTML or PNG have sadly limited resolution in bokeh. 
Problem is: I have to uncomment the SVG-part most of the time because the file generation takes about 10sec. This waiting time is only okay if I really want to use the plot later.
I would try to build a svg-export-button but I don't want to change to much things because I implement all my little changes in all of your new releases for testing.

**Comment by cutright** [comment]
I'll look into SVG generation.  I wonder where the bottleneck is?

I was able to cut down the dose interpolation time down by a factor of 100 by limiting my use of pure python functions.  Perhaps there's some room for improvement on the SVG conversion.

**Comment by cutright** [comment]
Just curious, did you use Bokeh itself to generate SVG files?  And when you say 10sec, is that per plot or do all plots get generated in this time?
https://docs.bokeh.org/en/latest/docs/user_guide/export.html#svg-generation

I could add a "Plot to svg" using Bokeh like I do for html.  And similarly so for the multi-variable regressions and machine learning plots within their modules...  hopefully the additional required libraries don't cause issues with PyInstaller.

<img width="765" alt="Screen Shot 2020-03-18 at 9 19 24 PM" src="https://user-images.githubusercontent.com/4778878/77025073-37122600-695e-11ea-8287-d89f6843b2d2.png">

**Comment by cutright** [comment]
Based on the lag I'm seeing for one plot generation, I'm going to guess the 10sec occurs because you have it create an svg every time a plot is generated?  Give DVHA's `svg_test` branch a shot.  I added a "Plot to svg" sub-menu just under "Plot to html".  It appears to work... but you'll need to do:
* `pip install selenium`
* `conda install phantomjs` or `npm install phantomjs`

I had to install `npm` through home-brew first.  I just prefer to avoid anaconda if at all possible.  Hopefully, I can figure out how to include `phantomjs` with PyInstaller.

**Comment by Kiragroh** [comment]
I use svg every time a DVH is generated and only for DVHs so far.
Your solution would be a nice implementation. 
I had do install Selenium and phantomjs, too (and fuzzywuzzy for some reason). Sadly I used conda to install phantomjs because the homebrew method did not work immediately but admittetly I didnt troubleshoot very much.

**Comment by cutright** [comment]
It looks like bokeh supports exporting svg with transparent background and plot borders as well.  I'll add these options to DVHA.

But I'm concerned about my ability to test this on Windows since I don't have admin privileges at work. And I'm unsure if I'll be able to include phantomjs with PyInstaller for DVHA executables.  But at a minimum, I can call this an "advanced feature" and leave it to the user to get phantomjs installed.

**Comment by Kiragroh** [comment]
here is my code for automatically copy a dvh plot to disk in specific size (png, html and svg) for every query. I only activate this if needed but your implementation will solve this in GUI. Very nice.

from bokeh.io.export import get_layout_html, export_png, export_svgs from bokeh.plotting import figure, output_file, save
...
def update_plot(self, dvh, dvh_2=None): 
… 
self.figure.y_range.start = -0.0005 self.figure.x_range.start = 0 
self.figure.y_range.end = 1.0005
 self.figure.background_fill_color = None 
self.figure.border_fill_color = None
  self.figure.plot_height=600 
self.figure.plot_width=820 
output_file("/Users/Max/Apps/dvh_analytics/data/plot.html")
 save(self.figure)
 self.set_figure_dimensions()  
#export_png(self.figure, filename="/Users/Max/Apps/dvh_analytics/data/plot.png", height=600, width=820)
 self.figure.output_backend = "svg" 
export_svgs(self.figure, filename="/Users/Max/Apps/dvh_analytics/data/plot.svg", height=600, width=820)
...
def update_plot_2(self, dvh_2):
 … 
self.figure.plot_height = 600 
self.figure.plot_width = 820 
output_file("/Users/Max/Apps/dvh_analytics/data/plot2.html") 
save(self.figure) 
self.set_figure_dimensions() 
export_svgs(self.figure, filename="/Users/Max/Apps/dvh_analytics/data/plot2.svg", height=600, width=820)

**Comment by cutright** [comment]
Thanks for sharing, letting the user customize the figure dimensions is a great idea.

**Comment by cutright** [comment]
Now there is only one menu item for figure export (still just in `v0.7.5dev` branch).  The custom figure properties currently only apply to SVG, will add to html soon.  I think I will store your previously used custom figure properties for each plot type.

If a property text field is empty, the figure's current value is used.

Any other suggestions for this feature while I'm focused on it?  I'm considering adding PNG support too since Bokeh has that function, but it depends on WebKit which could be complicated for Windows users.

<img width="1558" alt="Screen Shot 2020-04-06 at 10 10 34 AM" src="https://user-images.githubusercontent.com/4778878/78573911-e4a28780-77ee-11ea-9fe9-0edfbc352c11.png">

**Comment by Kiragroh** [comment]
Hi Dan,
the changes for 0.7.5 look amazing. 
I would honestly prefer PNG but the quality is not nice. SVG is the only format in high resolution.
This week I am not working but next week is HomeOffice and I will try the dev-version.

Here are some suggestions I would personally prefer or things I tried:
- checkboxes for Min, Max, Mean and Median (maybe the user doesn't want all of these in the image)
- a multiplicator for the thickness of lines or one hard coded thickness the user can change
- similar layout and export functionality for the integration of DVHcheck
- I played with the code for IQR and changed it to standard deviation (1sigma-mean and 1sigma+mean). It works but the problem is that the calculation is based of all y values for one x value and the result does not look nice (standard deviation below 0% and above 100% -> good thing these values are cut but the new default settings^^)

Keep up the good work. I am excited to test the changes next week.

**Comment by cutright** [comment]
> * checkboxes for Min, Max, Mean and Median (maybe the user doesn't want all of these in the image) 
> * a multiplicator for the thickness of lines or one hard coded thickness the user can change

You could edit the line widths and IQR alpha in User Settings.  And I think I'll add alpha options for the DVH stats line, since setting to a width of zero doesn't hide them. The minimum alpha is currently 0.1, but I'll push a min of 0.0 in the next dev push.

There is a bug that makes you restart DVHA for new options to take effect.  I'll look into that rather than adding a lot to the export figure window.  And I'll think about implementing temporary User Settings while exporting.

<img width="300" alt="Screen Shot 2020-04-08 at 1 18 22 PM" src="https://user-images.githubusercontent.com/4778878/78819195-74853480-799b-11ea-8fec-74694bb9e787.png">

> * I played with the code for IQR and changed it to standard deviation (1sigma-mean and 1sigma+mean). It works but the problem is that the calculation is based of all y values for one x value and the result does not look nice (standard deviation below 0% and above 100% -> good thing these values are cut but the new default settings^^)

https://github.com/cutright/DVH-Analytics/blob/faa999e7f2145195c00b76aa0c82b7902a5d7bbc/dvha/models/dvh.py#L297-L319

That's actually fairly easy to implement.  Just change line 312 from above to the following.

```
mean = np.mean(dvhs, 1)
std = np.std(dvhs, 1)
standard_stat_dvh = {'min': np.min(dvhs, 1),
                     'q1': mean - std,
                     'mean': mean,
                     'median': np.median(dvhs, 1),
                     'q3': mean + std,
                     'max': np.max(dvhs, 1)}
```

This "works", but these standards deviations are not bound by (0, 1) and I'm not sure the usual methods for a standard deviation calculation are valid for DVHs. @arkaroy1 Any thoughts about a standard deviation based region vs IQR?

@Kiragroh I think you allude to this, but didn't follow the based on all y values part, so not sure if you calculated the same way?

<img width="1000" alt="Screen Shot 2020-04-08 at 1 46 16 PM" src="https://user-images.githubusercontent.com/4778878/78821618-66d1ae00-799f-11ea-91a2-7002a98afab4.png">

**Comment by cutright** [comment]
OK, I think this new feature is pretty neat and it makes picking your plot options lot easier.  I figured out how to propagate plot options without restarting DVHA and I changed User Settings and the Export Figure windows to floating frames rather than modal dialog windows, so now you can have all of them open at once.

You can keep the User Settings window open and click apply to see the changes, if you hit cancel it will restore the previously saved options.

The Export Figure window will export whatever options are currently applied (not necessarily what's in your saved options).

This required a pretty significant rewrite of `dvha.models.plots`... hopefully I didn't mix up any options.

<s>I think all that's left is to let you set line alphas.</s>  Correction, this was already available in the alpha dropdown.

<img width="1680" alt="Screen Shot 2020-04-08 at 6 36 25 PM" src="https://user-images.githubusercontent.com/4778878/78843310-19b60200-79c8-11ea-8dda-26093689630b.png">

**Comment by cutright** [comment]
I think everything in this thread is implemented, other than the std deviation discussion.  If we come up with an eloquent way to handle that, let's just create a new issue since this thread is all over the place.

Pushing 0.7.5 momentarily.

**Comment by cutright** [comment]
After trial and error all day, I finally figured out how to include `PhantomJS` without additional installations, whether you are running DVHA from source or a PyInstaller freeze.  I just posted a new Windows executable on the [releases page](https://github.com/cutright/DVH-Analytics/releases/tag/v0.7.5).  Presumably macOS implementation will be similar.  

There is a new branch `v0.7.5post2-Windows` with these changes.  When running from source, the only thing is you need to download PhantomJS from [here](https://phantomjs.org/download.html) and place it in `dvha/PhantomJS/bin`.  I'm a little unsure about whether or not to include this file in my GitHub.  However, phantomjs.exe is included in the PyInstaller exe.

I call the following function in dvha_app.py.  The only curious thing is that this does not work with a PyInstaller freeze if `console=False` in the `.spec` file.

https://github.com/cutright/DVH-Analytics/blob/097f24e4149f0ebcee84ec1da3d7c794bcd6c8dd/dvha/tools/utilities.py#L774-L783

The downside is `PhantomJS` is 16MB for MSW and 45MB for macOS.  Maybe I find some others uses with `PhantomJS` with all of that overhead.  I'm hoping I can use it instead of an IE emulation for windows with wxPython, but I have no clear answer on that yet.
