### ISSUE TITLE
deactivate doseSum function?

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#57]
Here is my problem with the dose summation.
I have cases with the same StudyUID and multiple plans of intracranial stereotactic cases of different PTVs in the brain. First of all the summation do not work for these cohort (Import freeze or quit and no query results). 
But even if the summation would work, it makes no sense for - in some cases - different fractionation schemes (not biological equivalent).
Here my question:
Is there a simple way to deactivate this feature, add a button in the importer or change the code that dose summation will not take place if ...

My workaround:
I anomynize the extra plans (>1 plans) and therefore every patient only has one plan. With this trick my patient cohort works fine with DVHA.

**Comment by cutright** [comment]
I have just a few questions before adding a dose summation deactivation because it might not be trivial:
* Do all of these plans use the same structure set (i.e., same SOPInstanceUID)?
* Which TPS are you using?

-------------------------------------------------------
Unfortunately, DVHA is not designed for multiple DVHs assigned to the same structure (*currently*).  My clinic is looking to use DVHA for SRS and this is one of the issues we've come across.  The real issue stems from me not knowing how to properly setup a good SQL database... I did not create primary keys and instead used `study_instance_uid` + `roi_name` as a unique row identifier (bad form, I now know).

I *think* what makes sense is to let  DVHA (in its current framework) split a patient study (read StudyInstanceUID) into a new "patient" per plan (and append something to the end of the new StudyInstanceUID).  Then let DVHA follow the same import process for independent patients.  I believe that is effectively what your work-around is?

DVHA is designed to make it difficult for you to unknowingly reimport a patient.  But clearly there is some middle ground to be attained (or maybe just all-around better methods).  I'm thinking about storing a composite DVH and a plan DVH in the database.  This requires some structural changes as I noted in [this](https://github.com/cutright/DVH-Analytics/issues/44) issue.

**Comment by Kiragroh** [comment]
Thanks for the quick reply.
My TPS is Eclipse and I have cases with one structure set for multiple plans (here I mean with plan: RTdose+RTplan) and cases with seperate StructureSets. I could try to generate an anonymized dataset on friday and post it here if this helps but it sounds you incountered the problem before.

**Comment by cutright** [comment]
I don't think an anonymized set is needed.

I think there is an alternative work-around, you could import one plan at a time.
* Uncheck the plans to skip
* Be sure the "Leave files in inbox" option is checked
    * this should stick from your previous successful import
* Manually edit the Study Instance UID on the Import window (it's just a text field).
* Repeat

But if you have a TON of patients, this is maybe more work depending on your anonymization process.

Now that I've thought this through, I think it's maybe not too difficult to implement.  I'll plan to have this in 0.7.5.

By the way, the ones that freeze... do they happen to have 1mm dose grid resolutions?  I wonder if it's a memory allocation issue... or if maybe it just takes much longer than you expect?  I'd like to implement some notification of progress to the GUI, but it's not trivial at the moment.

**Comment by Kiragroh** [comment]
Thanks for the help and the planned implementation.
Ye, the dose grid is 1mm because my test cohort are all SRS plans.
I used your suggested workaround before 😊 but it is too much work because I had to do it every time I started with a fresh database and for testing I often delete all imported data and start from scratch.

**Comment by cutright** [comment]
The v0.7.5dev branch now supports dicompyler-core's `from_dicom_dvh`.

I still need to test it since I don't have any DICOM RT-Dose files with DVHs at home.  I think this will be helpful for those 1mm dose grids, particularly since Eclipse is so much faster than dicompyler-core (no offense @bastula... it's a tough problem, I really wonder how they do it so quickly... GPU maybe?).

If this works out, I'll do a better job of alerting the user which method was used for the DVH source.  At some point I'll alter the database to store this.  Unfortunately, SQLite doesn't have a `ADD COLUMN IF NOT EXISTS`, so I'm avoiding database edits as long as I can.

To enable, just go to the User Settings menu and check the "Import from DICOM DVH if available".
<img width="300" alt="Screen Shot 2020-03-22 at 10 45 43 AM" src="https://user-images.githubusercontent.com/4778878/77253747-4c22d980-6c2a-11ea-8cbf-1217f39ad717.png">

**Comment by cutright** [comment]
This issue is partially resolved in the `v0.7.5dev` branch.  You can uncheck "Sum all dose grids in a ~~patient~~ study" in the bottom left of the import screen.

However, now I need to keep track of PTVs per plan.  Currently, all PTV overlap and distance calculations are still based on a composite PTV.

**Comment by cutright** [comment]
@Kiragroh, I think the `v0.7.5dev` branch solves this issue.  Sorry for the delay.

Now if you have any multi-plan/single-structure studies (and you unchecked "Sum all dose grids in a study" on the bottom left of the import screen), you'll get a prompt to assign PTVs to specific plans for the composite PTV generation used for PTV Distance and Overlap calculations.

<img width="1462" alt="Screen Shot 2020-04-05 at 5 54 38 PM" src="https://user-images.githubusercontent.com/4778878/78512019-c8f39e80-7766-11ea-9256-8d1365293ec9.png">


I'll push this to master shortly... after I wrap-up a couple other smaller issues

**Comment by Kiragroh** [comment]
Hi,
I tried to import DICOM-Data without DoseSummation but it doesn't work. Maybe you have time to check with my DICOM-Files (anonymized). I get a plan-UID-key-Error. Is there a easy solution for this?

https://brewkvx-my.sharepoint.com/:u:/g/personal/m510001_365vipnow_com/EbyqzWzmrYZGhaupvTtwksABX98vARuMdK9C2Tk5GoTUIw?e=Y86FzF

Thanks for your very good work on this.

**Comment by cutright** [comment]
Taking a look now. Looks like I have a bug in the new PTV assignment work-flow.

**Comment by cutright** [comment]
Hopefully this fixes it?  Just added line 1724 below.  The only thing the PTV assignments in the no-dose-sum work-flow affects is PTV distance and overlap calculations.  It's worth verifying on your end that it's combining the correct PTVs (maybe validating the PTV overlap volumes against your TPS).

`pip install dvha==0.7.5.post2 --upgrade`

It's also on the latest version of the master branch if you don't do `pip`.

https://github.com/cutright/DVH-Analytics/blob/65a099880f332d2ddeffcbd3ac93f2ee6ba0b1aa/dvha/models/import_dicom.py#L1722-L1727

**Comment by Kiragroh** [comment]
Thanks for the quick fix. 
Now the import progress is starting. I will check in the morning if everything completed correctly (I just started a 70 plan import of highRes-data).

**Comment by cutright** [comment]
Just had a thought, if you're using PostgreSQL, I bet you could open multiple instances of DVHA simultaneously and split up your files, to take advantage of more CPU.  This would definitely be a problem if you use SQLite though.

**Comment by Kiragroh** [comment]
This is good to know. Thanks. 

The fix is working but I found another bug. I dont know why, but in one patient of mine one organ has the roi-type none and in this situation the import crash.

I attached the error and my quick&dirty 'try: except:'-solution

![IMG_5701](https://user-images.githubusercontent.com/44711812/79189098-31a2e100-7e21-11ea-8d08-50d0412d0195.jpg)

![IMG_5702](https://user-images.githubusercontent.com/44711812/79189107-35cefe80-7e21-11ea-9f89-1a6bc27fe1dd.jpg)

**Comment by Kiragroh** [comment]
Can you think of an easy way to visualize how many plans have to be processed in this extra import window?
For many plans it would be good to know how many clicks are left before the import process cann actually start.
![IMG_5703](https://user-images.githubusercontent.com/44711812/79189490-2e5c2500-7e22-11ea-9b7b-2e10e1ad1ad1.jpg)

**Comment by cutright** [comment]
Yes, that's very easy.  Good idea! Will push with `v0.7.6` tomorrow.

For the crash fix, it looks like this will happen any time ROI type is `None`.  I thought these were always stored as strings rather than `None-Type`, but apparently not.

In python `str(None)` returns `'None'`, so you could simply change `roi_type.lower()` to `str(roi_type).lower()`.  I'll include these changes in `v0.7.6`.

Thanks again for reporting these bugs.

**Comment by cutright** [comment]
<s>I think the numbers are incorrect right now, but that's how it will look.</s>
Turns out they are correct

<img width="1462" alt="Screen Shot 2020-04-14 at 8 26 58 AM" src="https://user-images.githubusercontent.com/4778878/79230187-d45f5d80-7e29-11ea-8070-405e91f5fb96.png">

**Comment by Kiragroh** [comment]
Perfect

**Comment by cutright** [comment]
The reason the number of patients in the PTV assignment didn't match my initial expectation is because one of the patients you sent has two separate study instances UIDs, so it didn't need to do the PTV assignment work-flow.  So I think it's working as it should.
