### ISSUE TITLE
Idea for additional feature

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#70]
Hi Dan,

I really like the frequent updates. I will try 0.7.8 right now.

Today, I had an idea. I think it would be nice to add a label-function for the importer. 

Say I have a big DICOM data set from clinic A and one from clinic B but all anonymized. Firstly, I import data set A and give a label to the first plan and apply this to the remaining plans. After this, I import the data from clinic B and can then compare specific things between them.

Let me know what you think about it.
Kind regards
Max

**Comment by cutright** [comment]
This is definitely a good thought, since one of my goals is for people to have multi-institutional studies. I think the only way to do this is to store the institution name in the SQL database.

I've been avoiding features that require alterations to the database since I added SQLite.  Mostly because I just haven't had time to investigate how altering tables affect SQLite... maybe it's not a big deal.

You could probably get the same simply by specifying which Tx Machine was used. And maybe combined with physician or TPS vendor... although I'd need to add that as an option in the dropdowns (not hard to do).  If this is a lot of things to add and you'd do it frequently, you could save the DVHA session, then load it and edit the query.

Let me give it some more thought, I have a feeling there's an easy solution.

**Comment by Kiragroh** [comment]
I use this combination of filters before to get a specific cohort of plans but I think a label would help to categories incoming data for different studies even if some departments use a strong anonymizer.
Hopefully, there is an easy way to accomplish this. Maybe these cases are rare and much work would be not efficient.

**Comment by cutright** [comment]
I'm guessing the easiest way is to add an Institution column to the Plans table.  I'd need to add another block on the import screen too.

**Comment by Kiragroh** [comment]
Hi Dan,

for an older plan study I created a cumulative dvh of all relevant structures (see picture). I used the R-programm "dvh-metrics" for building mean and standard deviation for every structure from exported Eclipse-DVH-Files and then used OriginPro to make a nice plot. Do you plan to add a nice dvh-builder for more than 2 Querys in the future?
No problem if you dont plan to do this. Then I will export the generated dvh-data for each structure and maybe write a python program to combine all exports in one nice plot.

I am curious: Are you making progress in implementing DVHchecker?

![Gesamt+legend](https://user-images.githubusercontent.com/44711812/81284805-e4501300-905e-11ea-91cd-df9a065f0451.png)

**Comment by cutright** [comment]
Unfortunately, the plotting code was almost entirely borrowed from the bokeh version, before I had much programming experience.  Even getting the 2nd group added was fairly painful.

If I may, since I know you're comfortable editing the code-base... you might have an easier time pickling the DVH class objects after each query.  In `dvha/main.py`, `self.group_data[1]['dvh']` and `self.group_data[2]['dvh']` are the `DVH` class objects from `dvha.models.dvh`.

https://github.com/cutright/DVH-Analytics/blob/800031b047faefdb66dcf52645d7b793e11daaf1/dvha/main.py#L668-L669

Maybe add something on line 770 like:
`pickle.dump(self.group_data[1]['dvh'], out_file_path)`

Then all you need to do is work with the numpy data objects in there, I think there's enough information below.

The actual DVH data lives in a 2D numpy array `DVH.dvh` with bin size of `DVH.dvh_bin_width` and dimensions of bins x number of DVHs. You can get a dictionary of stat DVHs with `DVH.get_standard_stat_dvh()`.  You can get your x_axis with the `x_data` property linked below.  It's basically the x-axis data repeated for each DVH... it seems like a waste of memory, but that's just how bokeh works for these multi-line plots.  Anyways, just take any element from `x_data` for your x-axis.

 The order of the `DVH.dvh` (if it matters to you) is in the order of the`DVH.uid` or `DVH.mrn` lists.  `DVH.x_data` and `DVH.y_data` are properties that return 2D arrays suitable for Bokeh, so they might be helpful for you.
https://github.com/cutright/DVH-Analytics/blob/800031b047faefdb66dcf52645d7b793e11daaf1/dvha/models/dvh.py#L159-L187

Lastly, you can check `dvha.models.plot.PlotStatDVH.update_plot` for an example of how I actually plot the data from the `dvha.models.dvh.DVH` object.
https://github.com/cutright/DVH-Analytics/blob/800031b047faefdb66dcf52645d7b793e11daaf1/dvha/models/plot.py#L398

**Comment by cutright** [comment]
With respect to the DVH check, unfortunately my time is being divided elsewhere for the time being.  However, I am committed to addressing bugs fairly quickly and can still make time to answer questions.

**Comment by cutright** [comment]
Actually... no need for you to edit DVHA code at all!  I just remembered that DVHA can save your session which is a pickle file including the DVH class object above.

```
>>> import pickle
>>> with open('test.dvha', 'rb') as infile:
            data = pickle.load(infile)    
>>> list(data['group_data'][1])
['dvh', 'data', 'stats_data']
>>> data['group_data'][1]['dvh']
<dvha.models.dvh.DVH object at 0x106954a90>
```

**Comment by Kiragroh** [comment]
Thanks for your quick reply and helpful suggestions. I will definitely try it in future projects.

**Comment by cutright** [comment]
I'm adding some notes in the manual about working with the `.dvha` file directly in python.  I'll include some basic examples for plotting with matplotlib.  I think this will be much more accessible rather than users perusing the entire DVHA code or figuring out how Bokeh works.

**Comment by cutright** [comment]
I'll put some more examples in the manual, but here's a start.

The `dvha.models.dvh.DVH` class has a property for each column in the DVHs table, with the exception of `dvh_string` since that's parsed into numerical data. Below is example code to plot a single DVH from a `.dvha` file.

```
import matplotlib.pyplot as plt
import pickle

# load the dvha session file and then store the group_1 dvh data
with open('test.dvha', 'rb') as infile:
    dvha_session_data = pickle.load(infile)
dvh = dvha_session_data['group_data'][1]['dvh']

i = 0 # change this index to pick a different DVH

# Collect the plotting data
x = dvh.x_data[i]
y = dvh.y_data[i]
mrn = dvh.mrn[i]
roi_name = dvh.roi_name[i]
title = '%s DVH for %s' % (roi_name, mrn)

# Create the plot, may need to call plt.show() on some setups
p = plt.plot(x, y)
plt.title(title)
plt.xlabel('Dose (cGy)')
plt.ylabel('Relative Volume')
```

<img width="752" alt="Screen Shot 2020-05-07 at 1 21 44 PM" src="https://user-images.githubusercontent.com/4778878/81335988-19179680-906e-11ea-9bd1-15ef6b4766bd.png">

**Comment by cutright** [comment]
I replaced the manual in the `v0.7.9` release with a [new](https://github.com/cutright/DVH-Analytics/releases/download/v0.7.9/DVHA-v0.7.9-Manual.pdf) version.

Pages 29-32 describe some ways to use the `.dvha` save file with python:
* Get the DVHA version
* Get the query used for the session
* Plot a DVH
* Calculate population DVHs
* Rescale DVHs to relative and absolute axes
* Extract endpoint and radbio table data that was used in the GUI

**Comment by cutright** [comment]
Just had a thought... what If I allow the user to specify a different DB connection for each group?

It would actually be a lot easier to do this and also provide a tool that dumps your PostgreSQL database to SQLite or JSON for easy sharing (for those uncomfortable with manual DB migration).

**Comment by Kiragroh** [comment]
Sounds awesome. See no problems with this solution. 
An additional benefit would be that you can delete a specific group easily from the database. Can you configure these in GUI also?
Thanks for your efforts.

**Comment by cutright** [comment]
Now in the `v0.8.1dev` branch:

I think the most intuitive way to implement this is to only allow this alternate connection to your main app queries.  Everywhere else will refer to your main connection settings (i.e., Database Administrator and DICOM Import).

In the menu bar under "Settings", there is now a "Database Connection 2" that generates the following window:

<img width="350" alt="Screen Shot 2020-05-16 at 5 42 07 PM" src="https://user-images.githubusercontent.com/4778878/82131613-9b096d00-979c-11ea-97bc-2bb5a1da31db.png">


If "Sync to Group 1" is checked, then the Group 2 settings will be ignored... but still stored in your options so you don't have to set it again when you re-enable a different Group 2 setting.

I think the only concern here is with the DVHs tab since Group 1 and Group 2 are merged for this view.  So if your query includes an ROI Name associated with the same StudyInstanceUID in both databases, I'm not sure which one will be selected and one will be thrown out.  I should add a group column and only merge (so it says group 1 & 2) if the StudyInstanceUID and complete DVH match... or maybe a hash of the DVH if that's faster.

**Comment by cutright** [comment]
In order to do this, I changed the structure of the `Options` class.  While I wrote a method to automatically upgrade your options file if needed, it is not backwards compatible.  If you run `>=v0.8.1dev`, then try to run a previous version, you'll get an ambiguous crash in the GUI but this error in the error log:

```
2020-05-17 10:42:12,331 - dvha - ERROR - Unhandled exception: Traceback (most recent call last):
  File "wx/core.py", line 3285, in <lambda>
  File "DVH-Analytics/dvha/main.py", line 537, in __catch_failed_sql_connection_on_app_launch
  File "DVH-Analytics/dvha/db/sql_connector.py", line 648, in initialize_db
  File "DVH-Analytics/dvha/db/sql_connector.py", line 42, in __init__
TypeError: unhashable type: 'dict'
```

To downgrade your options so you can run previous versions again, make sure you have the latest `v0.8.1dev`, then go to a python console and run:
```
from dvha.options import db_group_downgrade
db_group_downgrade()
```

**Comment by cutright** [comment]
Export of PGSQL to SQLite appears to transfer all data types properly and DVHA behaves when using the new SQLite DB. Opted for a slower implementation that queries one `StudyInstanceUID` at a time to avoid querying an entire table at once.

**Comment by cutright** [comment]
You no longer need to worry about that `db_group_downgrade()`... everything should be compatible now.  However, if you downgrade to <=0.8.0 after using >=0.8.1, the stored SQL connection will be either default values or the values from the last time you used a version <=0.8.0.

This level of detail probably isn't needed... worst-case scenario is you don't remember your PostgreSQL credentials, you can just use pickle to load `.options` to see it.  The new options file doesn't delete any data... just starts using `DB_TYPE_GRPS`, `SQL_LAST_CNX_GRPS` in lieu of `DB_TYPE`, `SQL_LAST_CNX`.

Will push a release today.

**Comment by cutright** [comment]
@Kiragroh FYI, if you're interested, I added an explanation of how to merge databases in section 1.1.4 of the [updated v0.8.1 manual](https://github.com/cutright/DVH-Analytics/releases/download/v0.8.1/DVHA-v0.8.1-Manual-Update.pdf) using the python console.

I feel like this isn't meant for common users, so I opted not to include it in the GUI.  Many more details in the PDF, but basically it's just this:
```
# Import Group 2 into Group 1, ignoring StudyInstanceUID conflicts
from dvha.db.sql_connector import DVH_SQL

with DVH_SQL() as cnx_dst:
    with DVH_SQL(group=2) as cnx_src:
        cnx_src.import_db(cnx_src, cnx_dst, force=True)
```

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/db/sql_connector.py#L625-L658
