### ISSUE TITLE
ROI-Map with organ type

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#81]
Hi Dan,

I process a little plan study from 5 top TPS (Pinnacle, Eclipse, Tomotherapy, Raystation and Monaco) right now.

The import is working without problems. But I had the idea that it would be nice when ROI Map could also define ROI-Type (when an entry is set in the .roi-file) too. 

At the moment the ROI type is set from DICOM-info. The problem is that many people change the appropriate ROI-type to trick the optimizer (or some other reason). In my case I had to manually change many ROI-Types in Import-Window to get the right ptv calculations at the end.

Do you think that would be good?

Best regards
Max

**Comment by cutright** [comment]
Changing the .roi file structure is not ideal since I think it would have to break previous DVHA versions.  But maybe a second file per physician linking Physician ROI to targets.  I'll have to give it some thought to see if there's an easy solution.

Do you think the target type should have been caught based on its name?  Maybe the current auto-detection just needs a tweak?

**Comment by Kiragroh** [comment]
Do you really think it is difficult for inter-version compatibility to change the code to look for an extra value at the end of a row in the roi-file?

I thought it could be possible with an IF-Statement: If last entry is empty use dicom Roi-type.

But I understand that this should mean that many parts has to be changed to make it work perfectly.

Maybe a alternative would be to remember the roiType definition of a certain foubd structure for the rest of the import process.

**Comment by cutright** [comment]
The issue is the previous versions of DVHA don't have that if statement... so the trick is what line of text to add to the .roi that the previous versions will ignore.  I don't think there's a solution to that because of how I coded the .roi parser.  I think it's easier for new version to check for the existence of this new roi type file and parse it if available.

A really easy partial solution would be to query your database for the physician roi and use the most common roi type.  The only downside to this method is it doesn't help when you have a fresh database.  But this would be only a few lines of code.

Your last comment is an interesting idea.  Basically let the user apply a global roi type override to all Structure sets in the import session (for a given physician roi)? Or maybe a multi-select and a select all button?  That would be more complicated than the query method above... but at least isolated to one module and no structural changes to files needed.

I'm leaning towards a combination of these two.  It honestly shouldn't be much work to implement.

**Comment by cutright** [comment]
A quick side comment, I'm concerned with backward-compatibility in case I make a release that has unforeseen bugs and then a user needs to downgrade.  It feels like the frequency of bug reporting is dropping, but since I'm the only coder and I frankly have no unit tests... backward-compatibility is the least I can do.

**Comment by cutright** [comment]
The ROI Name Manager will read every line in the .roi file.

https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/tools/roi_name_manager.py#L252-L264

If you follow the chain down, every line gets processed.
https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/tools/roi_name_manager.py#L98-L101

And even if there are no variations, the physician_roi of that name gets overwritten.  So I just don't see a way to hack it being in the same file.  That said... making it a new file isn't a big deal.  The hard part is propagating that new information everywhere and letting users edit it.  Which is why I'm in favor of the over-ride idea at time of import combined with a SQL query to encourage a common answer.

**Comment by cutright** [comment]
`v0.8.3` will let you store an ROI type to a physician ROI.  I'll then store this in an `roi_type` pickle file with the `.roi` files.  This won't be forced, you'll still be able to over-ride on the import screen.

![Untitled](https://user-images.githubusercontent.com/4778878/83980387-e6fe8c00-a8da-11ea-9558-602814f2aa2f.jpg)

**Comment by Kiragroh** [comment]
Perfect. The next version will bring nice additions. Will make troubleshooting and testing so much easier. Thanks

**Comment by cutright** [comment]
So I *think* this is fully functional in the `0.8.3dev` branch.

There is now a `.rtype` file that gets created along with a `.roi` in `~Apps/dvh_analytics/preferences`. The `.rtype` file is a simple text file that stores `roi_type` for each `physcian_roi` with an `roi_type` that is not 'NONE'.  This is backwards compatible since DVHA versions until now would not consider a `.rtype` file.

When you are in the Import Module, an `roi_type` will default to this value, assuming the ROI is mapped and the value stored in your map is not 'NONE'. If you change the ROI Type in the Import GUI, it will be considered an over-ride and apply only to that specific ROI of that patient.  If you then click "Store in ROI Map", this new value will apply to all ROIs that map to the current physician roi for the current physician.  This does not get saved until you click "Save ROI Map" or "Import", although it will propagate to all patients currently staged for import.

If there is not an `roi_type` stored in the ROI Map, and the `roi_type` has not been overridden in the Import screen, the value found in DICOM will be used.

Two related issues I think should be changed:
* When clicking "Save ROI Map" in the Import module, this should remap your database like it does from the ROI Map module
* The progress window during the ROI Map database update doesn't seem to give any useful information

**Comment by cutright** [comment]
Both items at the end of last comment resolved.

The progress bars only change if the SQL database is actually edited.  The changes are based on `difflib` output using the `.roi` files, but that may find changes that don't affect the DB.  Just so it looks cleaner I ensure the gauges go to 100% before closing.

I also modified the `difflib` output to include roi_type changes.

NONE and IGNORED are now a roi_type options.  NONE is meant to signal DVHA to use the DICOM value (or override) instead.  But maybe you never want a physician ROI to have a meaningful ROI Type, so I added IGNORED for that case.
