### ISSUE TITLE
Unable to write to SQLite DB without OS Admin user

### ISSUE THREAD

**Issue by MohammadSalehi72** [cutright/DVH-Analytics#82]
Dear Dan
Today, I tried to install DVH-Analytic software for dvh analysis proposes. I tried to install it through the executable method. But after import necessary data (RT plan, RT dose, and RT structure), software closed automatically.
I also tried to clone the source code and run " python dvha_app.py" command in cmd and it returns an error:"     from rapidfuzz._fuzz import *
ImportError: DLL load failed: The specified module could not be found.".
All necessary dependencies were installed according to the requirement.txt file.

Os: Win10 (Version 1803)
Python: 3.6

Best Regards

**Comment by cutright** [comment]
Try downgrading rapidfuzz, I'm currently on `0.7.3` with my Mac, I'm guessing my MSW7 computer at work is on the same since I switched at the same time:
`pip install --force-reinstall rapidfuzz==0.7.3`

Sounds like rapidfuzz isn't submitting PyPI versions the same way every time.  I'll have to do some testing to figure out when rapidfuzz breaks DVHA.

**Comment by cutright** [comment]
By the way... can you check `~/Apps/dvh_analytics/data/logs`, specifically when you ran the executable?  Another user crashed at that time with the `PyInstaller` executable, but no errors were logged.

**Comment by cutright** [comment]
Which version of rapidfuzz do you have? Or maybe you can chime in with the referenced issue above in the RapidFuzz repository?

**Comment by cutright** [comment]
I think I should wrap the name prediction with a try/except clause to prevent a crash... especially since it's not a critical feature.  I'll add that for DVHA `v0.8.2`

**Comment by MohammadSalehi72** [comment]
Dear Dan

My RapidFuzz version is 0.7.6. Right now  I want to downgrade RapidFuzz version to 0.7.3 as you mentioned.
I also checked the /Apps/dvh_analytics/data/logs, and I found the dvha.log file, but it was an empty file.

**Comment by cutright** [comment]
If you're comfortable switching branches, can you give the `0.8.2` branch a shot?

I added a try/except clause: https://github.com/cutright/DVH-Analytics/commit/5081013bd36c5f371eab3c1c670066c719df5bc0

**Comment by MohammadSalehi72** [comment]
> If you're comfortable switching branches, can you give the `0.8.2` branch a shot?
> 
> I added a try/except clause: [5081013](https://github.com/cutright/DVH-Analytics/commit/5081013bd36c5f371eab3c1c670066c719df5bc0)

**Comment by MohammadSalehi72** [comment]
> If you're comfortable switching branches, can you give the `0.8.2` branch a shot?
> 
> I added a try/except clause: [5081013](https://github.com/cutright/DVH-Analytics/commit/5081013bd36c5f371eab3c1c670066c719df5bc0)

I made the changes you mentioned and this works. But now it has a problem in the DVH calculating, and it's been like that for a few minutes (screenshot).

![trub_2](https://user-images.githubusercontent.com/43685836/83357311-e9b02d00-a380-11ea-9a49-8634c9a7cc4f.png)

**Comment by cutright** [comment]
anything in your command prompt or the logs? `/Apps/dvh_analytics/data/logs`

**Comment by MohammadSalehi72** [comment]
No, dvha.log still is an empty file

**Comment by cutright** [comment]
And nothing in your command prompt?

**Comment by MohammadSalehi72** [comment]
I run dvha_app.py in cmd and there is nothing in command prompt appear while DVH calculation or anything else.

**Comment by cutright** [comment]
I'm guessing there's a crash at the first attempt to push data to the SQL database. If you go to the Database Administrator, change the table DVHs, then click Query... do you get any data?
<img width="1401" alt="Screen Shot 2020-05-31 at 12 32 28 PM" src="https://user-images.githubusercontent.com/4778878/83358695-ea25d500-a33a-11ea-9e02-a746da4561b8.png">


Are you an admin user on your computer? I'm wondering if there's a file rights issue with the SQLite db file.

Sounds like you might be pretty comfortable with python?  Do you mind adding a print statement before and after the `cnx.insert_data_set(data_to_import)` referenced below? And see if your command prompt prints the second statement?
https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/models/import_dicom.py#L1280-L1287

**Comment by MohammadSalehi72** [comment]
> I'm guessing there's a crash at the first attempt to push data to the SQL database. If you go to the Database Administrator, change the table DVHs, then click Query... do you get any data?
> <img alt="Screen Shot 2020-05-31 at 12 32 28 PM" width="1401" src="https://user-images.githubusercontent.com/4778878/83358695-ea25d500-a33a-11ea-9e02-a746da4561b8.png">
> 
> Are you an admin user on your computer? I'm wondering if there's a file rights issue with the SQLite db file.
> 
> Sounds like you might be pretty comfortable with python? Do you mind adding a print statement before and after the `cnx.insert_data_set(data_to_import)` referenced below? And see if your command prompt prints the second statement?
> https://github.com/cutright/DVH-Analytics/blob/dbbfc30feb3e93af3e36060655eebddef4f28413/dvha/models/import_dicom.py#L1280-L1287

Yes, in database administrator there is data after getting query. But there is no dvh calculated data after a click on the "Open" icon.
I also logged as an administrator in windows and also run command prompt as an administrator.
It seems it's work because this time it doesn't crash after import (RT plan, RT Dose, RT Structures).
Furthermore, after adding the print statement as you said, in the command prompt, a warning appears to say: 
"WARNING: No PTV found for mrn: ANON12314
        Skipping PTV related calculations."
Now my problem is how to find calculated dvh to import in software.
![new_pic](https://user-images.githubusercontent.com/43685836/83359430-719d3380-a38f-11ea-8d50-660a0f0bbb02.PNG)

**Comment by cutright** [comment]
OK, I think the real issue had to do with your user's privileges.  I'll have to see if there's a way I can catch that...

The warning happened because you did not assign any ROI as a PTV, but that just means the distance and volume overlap calculations are skipped.

Have you tried performing a query on the main page?  My guess is that everything is working as it should now.  If you're trying to look at a specific organ, you might need to import a few more plans... but for testing set your query to something  really loose like physician name or something.

**Comment by cutright** [comment]
I wonder if it has to do with one python process creating the DB and another pushing it?  I'm just speculating right now.  It's really unclear to me why it doesn't prompt an error in the console.

https://serverfault.com/questions/57596/why-do-i-get-sqlite-error-unable-to-open-database-file

**Comment by MohammadSalehi72** [comment]
Dear Dan

I think it's worked. I add a query filter (Physician, Default) in the categorical query, and the analyzed results appeared. 
The most important things, are those changes that you made on  "https://github.com/cutright/DVH-Analytics/commit/5081013bd36c5f371eab3c1c670066c719df5bc0" and this solved my problem.

In the next days, I'll do some analysis and get back to you if were any problems.

Thank you so much.

Best Ragards

**Comment by cutright** [comment]
That's great! Let's keep this issue open while I'll keep looking into the potential user privilege issue too.  Seems to me you shouldn't need admin privileges just to work with SQLite.

**Comment by cutright** [comment]
Screenshots and write test code below.  At least now, DVHA will check for its ability to write to your current SQL connection before beginning import.  I'm unsure if I should handle the rest or not.  I think it comes down to user privileges and how your OS assigns them when a file is created.  I could add a script to change the privileges... but given the sort of data that goes into this database, I'm not sure that's the right thing to do.  I'm leaning towards that being the responsibility of the user and their IT.  This is mostly because I cannot reproduce this scenario, so I'm hesitant to assume I know how to fix it.

https://github.com/cutright/DVH-Analytics/blob/19a1aaac409254e524f95e8cb019ba8affffb1dd/dvha/db/sql_connector.py#L720-L766

<img src="https://user-images.githubusercontent.com/4778878/83886459-b5d06100-a70c-11ea-8a56-2366281714be.png" alt="screenshot" width="500"/>

<img src="https://user-images.githubusercontent.com/4778878/83886562-d698b680-a70c-11ea-97ee-06d314980de6.png" alt="screenshot" width="400"/>


I'll leave this issue open for a little while in case anyone can offer a better solution or insight.  But at least DVHA won't hang anymore.
