### ISSUE TITLE
Graphs will not show

### ISSUE THREAD

**Issue by SotiriStathakis** [cutright/DVH-Analytics#90]
Hi,
I am new to python but I am very interested in the DVH analytics. I have recently installed DVH analytics on Windows 10 PC. I have imported a few patients but when we query the database the DVH, regression, correlation, etc graphs are not populated. 
What could be the issue?

Thank you in advance,

Sotiri Stathakis

**Comment by cutright** [comment]
Which version of Bokeh is installed?

**Comment by SotiriStathakis** [comment]
It is
bokeh-1.4.0-py3.8.egg

-S
________________________________

**Comment by cutright** [comment]
If you go into the Database Administrator, click on the "Query" button.  That should give you a table below of all imported plans.  Do any show up?

Do you get any errors on screen?  If you go to your Windows user folder ~/Apps/dvh_analytics/logs/dvha.log, does it say anything?

**Comment by cutright** [comment]
Also... are there any HTML files in ~/Apps/dvh_analytics/data/temp?  For the Windows version of DVHA, all of the plot views are stored there.

**Comment by SotiriStathakis** [comment]
The dvha log file is there but has no content. it is a 0KB file.
There are html files in the temp. I can open them if I double click them and direct IE to allow blocked content.
How do I fix IE not to block the graphs

Sotiri
________________________________

**Comment by cutright** [comment]
I was under the impression that issue was solved by this code:
https://github.com/cutright/DVH-Analytics/blob/c23031ab246128593487caf6efe68301290fb657/dvha/tools/windows_reg_edit.py#L38-L42

But perhaps not.  Maybe try editing your security settings in IE internet options directly?  Unfortunately, wxPython uses IE by default for their Windows webview object.  There's also a possibility you may need to be an admin user?  This is the first time I've seen this error a long time.

**Comment by SotiriStathakis** [comment]
Hi,
It seems that the problem is that the PC i am working on has the IE explorer restricted of using ActiveX. It is IT policy and they do not authorize it.
I wonder if there is a way to bypass the ActiveX.

Thank you for your help troubleshooting the issue.

Sotiri

________________________________

**Comment by cutright** [comment]
Honestly, getting DVHA to work on Windows at all has been the most frustrating part because its web emulation uses Internet Explorer (IE).  That's the reason I have to cap `Bokeh` at 1.4, I believe they stopped bothering to support IE on the next version (2.0)... and rightfully so...  IE is the worst.

There is a way to get wxPython to use Edge per their [documentation](https://wxpython.org/Phoenix/docs/html/wx.html2.WebView.html). Maybe you could have better luck than me?  It's only one more line of code on the DVHA side I think, but the rest has to do with your local environment... not sure if IT would let you do that either?

Worst case scenario, and it's kind of a crappy one... but you could manually open the plots from the temp folder with Chrome (there's a reasonable chance IT hasn't locked down the ability to run Chrome since you don't have to "install" it).

**Comment by cutright** [comment]
Just noticed this in the wxPython Discuss board.  Looks promising:
https://discuss.wxpython.org/t/ms-edge-backend-for-webview/34953

**Comment by cutright** [comment]
I was able to switch the backend to Edge, but the plots didn't show on screen.  I'll keep poking around.

**Comment by cutright** [comment]
Progress! I got Edge to work with the latest wxPython dev build, and its demo code works with DVHA's bokeh plots. Now just gotta figure out why DVHA won't display the web view when Edge is set as the backend. Also, the pan, box zoom, and legend interaction work with Edge!

![](https://discuss.wxpython.org/uploads/default/original/2X/7/740ca7574ba877687f1375de93069168893f01a7.jpeg)

**Comment by cutright** [comment]
Getting very close. It looks like the code to get this to work is very minimal.  However, there is a bug in `wxPython` that crashes Edge webviews not in the first `wx.Notebook` page.  Issue posted here: https://discuss.wxpython.org/t/ms-edge-backend-fails-in-notebook-other-than-first-page/35036

**Comment by cutright** [comment]
Making good progress finally.  I know what needs to be done at least.  I'll probably have MS Edge compatibility for v0.9.3.

![image](https://user-images.githubusercontent.com/4778878/104064735-11435f80-51c4-11eb-853f-d05d7608e7ec.png)

**Comment by cutright** [comment]
Finally! MS Edge is supported in the current v0.9.3 branch, for Windows users only (macOS works just fine, so no need to switch the web backend).
* Install the latest MS Edge Beta: https://www.microsoftedgeinsider.com/en-us/download
* Switch to the v0.9.3 branch, ensure wxPython>=4.1.1
* Click on the Setting gear icon in the tool bar
* Check "Enable Edge WebView Backend"
* Restart DVHA 

Note that I don't, at the moment, have a way to verify this is all you have to do, but I'm pretty sure that's all I did on my MSW7 computer at work.

**Comment by cutright** [comment]
Just posted a pre-release of v0.9.3, which includes a Windows executable and support for MS Edge backend.  Please read the release notes.

https://github.com/cutright/DVH-Analytics/releases/tag/v0.9.3.rc1

**Comment by cutright** [comment]
v0.9.3 has been released, if you install Edge beta per the release notes, I think this will resolve the ActiveX issue.
https://github.com/cutright/DVH-Analytics/releases/tag/v0.9.3
